# Generated by Django 5.0.1 on 2024-01-21 06:05

import wauthentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wauthentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextradetail',
            name='profile_image',
            field=models.ImageField(upload_to=wauthentication.models.user_profile_image_handler),
        ),
    ]
