# Generated by Django 5.0.1 on 2024-01-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wauthentication', '0002_alter_userextradetail_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextradetail',
            name='user_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
