# Generated by Django 5.0.1 on 2024-01-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wauthentication', '0003_userextradetail_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextradetail',
            name='user_bio',
        ),
    ]
