# Generated by Django 5.0.1 on 2024-01-28 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wauthentication', '0005_user_alter_userextradetail_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextradetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userextradetail',
            name='user_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
