# Generated by Django 5.0.1 on 2024-01-28 10:46

import wauthentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wauthentication', '0006_alter_userextradetail_user_userextradetail_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextradetail',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=wauthentication.models.user_profile_image_handler),
        ),
    ]
