# Generated by Django 5.0.1 on 2024-01-22 06:51

import socialapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=socialapp.models.post_image_handler),
        ),
    ]
