# Generated by Django 5.0.1 on 2024-01-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_post_category_comment_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('news', 'News'), ('food', 'Food'), ('travel', 'Travel')], default='All', max_length=50),
        ),
    ]
