# Generated by Django 5.0.1 on 2024-01-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0007_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liked',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='liked',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
