# Generated by Django 5.0.1 on 2024-01-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0008_remove_liked_liked_by_remove_liked_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('all', 'All'), ('food', 'Food'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('news', 'News'), ('sports', 'Sports'), ('business', 'Business'), ('learning', 'Learning'), ('music', 'Music')], default='all', max_length=120),
        ),
    ]
