# Generated by Django 5.0.1 on 2024-01-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0009_post_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_type',
            new_name='category',
        ),
    ]
