# Generated by Django 5.0.1 on 2024-02-10 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0036_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='liked',
            name='liked_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
